-- Persistence fields for grading and recommendation layers.
ALTER TABLE appraisals
    ADD COLUMN IF NOT EXISTS population_directness_label TEXT,
    ADD COLUMN IF NOT EXISTS population_directness_score SMALLINT,
    ADD COLUMN IF NOT EXISTS study_design_label TEXT,
    ADD COLUMN IF NOT EXISTS study_design_score SMALLINT,
    ADD COLUMN IF NOT EXISTS outcome_relevance_label TEXT,
    ADD COLUMN IF NOT EXISTS outcome_relevance_score SMALLINT,
    ADD COLUMN IF NOT EXISTS risk_of_bias_label TEXT,
    ADD COLUMN IF NOT EXISTS risk_of_bias_score SMALLINT,
    ADD COLUMN IF NOT EXISTS consistency_label TEXT,
    ADD COLUMN IF NOT EXISTS consistency_score SMALLINT,
    ADD COLUMN IF NOT EXISTS precision_label TEXT,
    ADD COLUMN IF NOT EXISTS precision_score SMALLINT,
    ADD COLUMN IF NOT EXISTS extrapolation_flag BOOLEAN,
    ADD COLUMN IF NOT EXISTS surrogate_only_outcomes BOOLEAN,
    ADD COLUMN IF NOT EXISTS overall_certainty_label TEXT,
    ADD COLUMN IF NOT EXISTS overall_certainty_score SMALLINT,
    ADD COLUMN IF NOT EXISTS grading_rationale_json JSONB,
    ADD COLUMN IF NOT EXISTS grading_downgrade_reasons_json JSONB,
    ADD COLUMN IF NOT EXISTS grader_confidence DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS recommendation_strength_label TEXT,
    ADD COLUMN IF NOT EXISTS recommendation_strength_score SMALLINT,
    ADD COLUMN IF NOT EXISTS benefit_harm_balance_label TEXT,
    ADD COLUMN IF NOT EXISTS benefit_harm_balance_score SMALLINT,
    ADD COLUMN IF NOT EXISTS feasibility_label TEXT,
    ADD COLUMN IF NOT EXISTS feasibility_score SMALLINT,
    ADD COLUMN IF NOT EXISTS preference_sensitivity_label TEXT,
    ADD COLUMN IF NOT EXISTS preference_sensitivity_score SMALLINT,
    ADD COLUMN IF NOT EXISTS population_applicability_label TEXT,
    ADD COLUMN IF NOT EXISTS population_applicability_score SMALLINT,
    ADD COLUMN IF NOT EXISTS recommendation_summary TEXT,
    ADD COLUMN IF NOT EXISTS recommendation_cautions_json JSONB,
    ADD COLUMN IF NOT EXISTS recommendation_rationale_json JSONB,
    ADD COLUMN IF NOT EXISTS recommendation_confidence DOUBLE PRECISION;
